# Generated by Django 3.2.9 on 2021-11-18 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0003_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='modified_date',
        ),
    ]
